name: 'Tencent CloudBase Github Action'
description: '云开发 Github Action 可以支持将你的项目一键部署到云开发环境'
author: bookerzhao
branding:
  icon: upload-cloud
  color: blue
inputs:
  secretId:
    description: '云开发 secretId'
    required: true
  secretKey:
    description: '云开发 secretKey'
    required: true
  envId:
    description: '云开发环境 Id'
    required: true

runs:
  using: 'composite'
  steps:
    - run: sudo bash ${{ github.action_path }}/@v2/run.sh ${{ inputs.secretId }} ${{ inputs.secretKey }} ${{ inputs.envId }}
      shell: bash
